version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '7777:7777'
    links:
      - mysql57

  mysql57:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'simple'
    expose:
    - '3306'
    volumes:
      - /data/db

